# Generated by Django 5.0 on 2023-12-10 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurantbranches_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantbranches',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurantcity'),
        ),
        migrations.AlterField(
            model_name='restaurantbranches',
            name='unique_id',
            field=models.CharField(default='1409364b', max_length=20, unique=True),
        ),
    ]
