# Generated by Django 5.0 on 2023-12-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantbranches_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbranches',
            name='unique_id',
            field=models.CharField(default='ef9bcb35', max_length=20, unique=True),
        ),
    ]
