# Generated by Django 5.0 on 2023-12-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_restaurantbranches_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbranches',
            name='unique_id',
            field=models.CharField(default='b0c8e9f1', max_length=20, unique=True),
        ),
    ]
