# Generated by Django 5.0 on 2023-12-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_alter_restaurantbranches_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbranches',
            name='unique_id',
            field=models.CharField(default='2020341f', max_length=20, unique=True),
        ),
    ]
