# Generated by Django 5.0 on 2023-12-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='contact_number',
            field=models.IntegerField(unique=True),
        ),
    ]
