# Generated by Django 5.0 on 2023-12-10 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerwallet',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
    ]
