# Generated by Django 5.0 on 2023-12-08 17:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('buy_price', models.IntegerField(max_length=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('get_price', models.IntegerField(max_length=10, validators=[django.core.validators.MaxValueValidator(5000)])),
                ('expire_at', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurantbranches')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed', models.BooleanField(default=False)),
                ('purchased_at', models.DateField(auto_now_add=True)),
                ('redeemed_at', models.DateField(default=None)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
                ('voucher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.vouchers')),
            ],
        ),
    ]
