# Generated by Django 5.0 on 2023-12-08 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='buy_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='get_price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
