# Generated by Django 5.0 on 2023-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_alter_vouchers_buy_price_alter_vouchers_get_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherhistory',
            name='redeemed_at',
            field=models.DateField(default=None, null=True),
        ),
    ]
