# Generated by Django 5.0 on 2023-12-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_alter_voucherhistory_redeemed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherhistory',
            name='redeemed_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
