# Generated by Django 5.0 on 2023-12-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurantbranches_unique_id'),
        ('vouchers', '0004_alter_voucherhistory_redeemed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='created_by',
        ),
        migrations.AddField(
            model_name='vouchers',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='VoucherRestaurantMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('restaurant_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurantbranches')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.vouchers')),
            ],
        ),
    ]
