# Generated by Django 5.0 on 2023-12-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurantbranches_unique_id'),
        ('vouchers', '0005_remove_vouchers_created_by_vouchers_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
